<?php declare(strict_types=1);

namespace steinmb\Logger;

use PHPUnit\Framework\TestCase;

class LoggerTest extends TestCase
{
    private $logger;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->logger = new Logger('Test');
        $this->logger->pushHandler(new NullHandler());
    }

    public function testWithName(): void
    {
        $logger2 = $this->logger->withName('Test2');
        self::assertSame('Test2', $logger2->getName());
    }

    public function testRead(): void
    {
        self::assertSame('Test data from NullHandler', $this->logger->read());
    }
}
